my_file = open("my_file.txt", "w")
my_file.writelines("I chose to write this line\n")
my_file.flush()
read_my_file = open("my_file.txt", "r")
print(read_my_file.read())
read_my_file.close()
my_file.close()
